### ISSUE TITLE
Weird Console Error

### ISSUE THREAD

**Issue by thodpap** [idkr-client/idkr#64] opened 2022-06-18 23:23 UTC
I run idkr on ubuntu 20 with the [Linux portable (x86_64)](https://github.com/idkr-client/idkr/releases/latest/download/idkr-portable-linux-x86_64.AppImage) image. After installing it i ran `chmod a+x idkr-portable-linux-x86_64.AppImage` to make it executable. After running it with `./idkr-portable-linux-x86_64.AppImage` i get the following error 

[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
idkr: ../../src/xcb_io.c:269: poll_for_event: Assertion '!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
 
Then I tried running it with `sudo ./idkr-portable-linux-x86_64.AppImage --no-sandbox` the no-sandbox is required for some reason. 
Initially, it worked, but the sound was off (don't know why). 
Now, trying the same thing fails and i get the same error message.
Am I doing something wrong or is it a bug?

**Comment by Mixaz017** [comment] 2022-06-19 00:26
This is duplicate of #21. Solution is also found there.

**Closed by Mixaz017** 2022-06-19 00:26 UTC
